name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.0.2"

      - name: Check
        run: "deno task check:all"

      - name: Install deployctl
        run: "deno install -gArf jsr:@deno/deployctl"

      - name: Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: "deployctl deploy --project=tba-api --prod ./api/main.ts"
